
name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  code_style_check:
    name: Code quality checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        working-directory: ./app
        run: npm i eslint eslint-config-prettier prettier
      
      - name: Run prettier checks
        working-directory: ./app
        run: npx prettier --check .
      
      - name: Run ESLint checks
        working-directory: ./app
        run: npx eslint .
      
  meteor_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: 2.7.3

      - name: Install dependencies
        run: meteor npm i
        working-directory: ./app
      
      - name: Run tests
        working-directory: ./app
        run: meteor npm test
