
name: WEBHOOK TEST

on:
  workflow_dispatch:

jobs:
  call:
    name: Call webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST request
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
